package uz.pdp.avtoticket.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * @author Baxriddinov Odiljon
 * @since 01/09/2025 14:01
 */

@Getter
@RequiredArgsConstructor
public enum PermissionType {
    // USER:
    VIEW_OWN_PROFILE("VIEW_OWN_PROFILE"),
    EDIT_OWN_PROFILE("EDIT_OWN_PROFILE"),
    BOOK_TICKETS("BOOK_TICKETS"),
    CANCEL_TICKETS("CANCEL_TICKETS"),
    VIEW_TICKET_HISTORY("VIEW_TICKET_HISTORY"),
    SEARCH_BUSES("SEARCH_BUSES"),
    SEARCH_ROUTES("SEARCH_ROUTES"),
    MAKE_PAYMENTS("MAKE_PAYMENTS"),
    RATE_TRIPS("RATE_TRIPS"),
    REVIEW_TRIPS("REVIEW_TRIPS"),

    // PASSENGER
    VIEW_AVAILABLE_TRIPS("VIEW_AVAILABLE_TRIPS"),
    VIEW_PERSONAL_TICKET_HISTORY("VIEW_PERSONAL_TICKET_HISTORY"),
    RECEIVE_NOTIFICATION_ABOUT_TRIPS("RECEIVE_NOTIFICATION_ABOUT_TRIPS"),

    // DRIVER
    VIEW_ASSIGNED_TRIPS("VIEW_ASSIGNED_TRIPS"),
    UPDATE_TRIP_STATUS("UPDATE_TRIP_STATUS"),
    VIEW_PASSENGER_LIST_FOR_ASSIGNED_TRIPS("VIEW_PASSENGER_LIST_FOR_ASSIGNED_TRIPS"),
    UPDATE_BUS_STATUS("UPDATE_BUS_STATUS"),
    COMMUNICATE_WITH_PASSENGERS("COMMUNICATE_WITH_PASSENGERS"), // optional notification/chat

    // ADMIN
    MANAGE_USERS("MANAGE_USERS"), // create, update, deactivate_accounts
    MANAGE_DRIVERS("MANAGE_DRIVERS"), // create, update, deactivate_accounts,
    MANAGE_TRIPS_AND_SCHEDULES("MANAGE_TRIPS_AND_SCHEDULES"),
    VIEW_ALL_BOOKINGS("VIEW_ALL_BOOKINGS"),
    GENERATE_REPORTS("GENERATE_REPORTS"),
    MODERATE_REVIEWS_AND_RATINGS("MODERATE_REVIEWS_AND_RATINGS"),
    MANAGE_PAYMENTS_OR_TRANSACTIONS("MANAGE_PAYMENTS_OR_TRANSACTIONS"), // view/ refund

    // SUPER_ADMIN
    ALL_ADMIN_PERMISSION("ALL_ADMIN_PERMISSION"),
    MANAGE_ROLES_AND_PERMISSIONS("MANAGE_ROLES_AND_PERMISSIONS"),
    MANAGE_SYSTEM_SETTINGS("MANAGE_SYSTEM_SETTINGS"),
    ACCESS_ALL_LOGS_AND_ANALYTICS("ACCESS_ALL_LOGS_AND_ANALYTICS"),
    EMERGENCY_ACTIONS("EMERGENCY_ACTIONS"); // delete context, block user permanently

    private final String access;
}